version: '2'
services:
  jhipsterdemo-app:
    image: jhipsterdemo
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://jhipsterdemo-mssql:1433;database=jhipsterDemo
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8080:8080
  jhipsterdemo-mssql:
    extends:
      file: mssql.yml
      service: jhipsterdemo-mssql
